### ISSUE TITLE
Does the alarm have documentation?

### ISSUE THREAD

**Issue by tangmingming** [apache/incubator-skywalking#1237]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [1 ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question

See the alarm function, but do not know how to use
--using Google Translate

**Comment by wu-sheng** [comment]
Please look your `application.yml` in your collector config directory. The following settings are alarm related. And I think it is easy to understand. 

```yaml
# alarm threshold
    applicationApdexThreshold: 2000
    serviceErrorRateThreshold: 10.00
    serviceAverageResponseTimeThreshold: 2000
    instanceErrorRateThreshold: 10.00
    instanceAverageResponseTimeThreshold: 2000
    applicationErrorRateThreshold: 10.00
    applicationAverageResponseTimeThreshold: 2000
```
