### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by akozichev** [apache/incubator-skywalking#1902]
Hello! In version 5.x collector configuration for UI connection(ui.jetty.host) works as a "binding" interface and URL to connect at the same time. 

It forces you to hardcode IP/DNS name of the server where collector will run into config file and makes it impossible to run collector and webapp in different pods on Kubernetes and/or behind proxies. 

Everything fine if both collector and webapp run on the same host or on the same flat network(no NAT, no proxy, no loadbalancers) - IP address on the interface of the collector which used to bind - is the same IP which is return to webapp to connect. 

If you run collector and webapp in Kubernetes or behind proxy/load balancer the IP addresses will be different, making effectively impossible to connect Webapp to Collector. 

The workaround I use in kubernetes - is to run collector and webapp on the same POD and pointing ui.jetty.host to 127.0.0.1

Is it possible to enable "direct connect" mode for UI -> collector or add configuration to separate "bind" option and URL to connect for webapp?

Andrey

**Comment by hanahmily** [comment]
The problem seems to bind the ipv4 interface to a static address. I suggest you change `ui.jetty.host` to `0.0.0.0`, which is suitable for collectors that do not know an ip address.

**Comment by akozichev** [comment]
I tried to set 0.0.0.0. But when I do it the Webapp fails to connect to collector, it looks like Collector's Nameserver  returns 0.0.0.0:12800 for Webapp to connect, which doesn't work. 
I couldn't find a way to connect Webapp to Collector "direct" bypassing the nameserver.
Perhaps v6 will work for me if it doesn't have same  issue, I haven't tried it yet.

**Comment by hanahmily** [comment]
Here my collector `config/application.yml`:
```yaml
ui:
  jetty:
    # Stay in `localhost` if UI starts up in default mode.
    # Change it to OS real network IP(binding required), if deploy collector in different machine.
    host: 0.0.0.0
    port: 12800
    contextPath: /
```

and UI `webapp/webapp.yml`
```yaml
collector:
  path: /graphql
  ribbon:
    ReadTimeout: 10000
    listOfServers: collector-svc:12800
```
then map the ip of collectors/loadbalancer to the `collector-svc` domain name.
