### ISSUE TITLE
skywalking 6.0-alpha ui dashboard don't display service

### ISSUE THREAD

**Issue by qdlake** [apache/incubator-skywalking#2010]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [*] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
## skywalking ui dashboard don't display service
___
### Bug
- Which version of SkyWalking, OS and JRE?
### 6.0 alpha,  linux, docker,  jre8
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

![ui](https://user-images.githubusercontent.com/1879819/49572242-59a14b00-f976-11e8-8e08-56bffdb18ac5.png)

docker-compose.yml
```yaml
version: "3.7"
services:
  elasticsearch:
    image: elasticsearch:6.5.1
    container_name: elasticsearch
    hostname: elasticsearch
    restart: always
    networks:
      - back-net
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ulimits:
      nproc: 65535
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    environment:
      - "TZ=Asia/Shanghai"
      - cluster.name=elasticsearch
      - discovery.type=single-node
      - XPACK_SECURITY_ENABLED=false
      - XPACK_MONITORING_ENABLED=false
      - XPACK_ML_ENABLED=false
      - XPACK_GRAPH_ENABLED=false
      - XPACK_WATCHER_ENABLED=false
      - bootstrap.memory_lock=true
      - discovery.zen.minimum_master_nodes=1
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
  skywalking-oap:
    image: skywalking-oap:v1
    container_name: skywalking-oap
    hostname: skywalking-oap
    restart: always
    volumes:
      - /docker/volumes/skywalking/config:/apache-skywalking-apm-incubating/config:ro
    networks:
      - back-net
    ports:
      - "11800:11800"
      - "12800:12800"
    depends_on:
      - elasticsearch
  skywalking-ui:
    image: skywalking-ui:v1
    container_name: skywalking-ui
    hostname: skywalking-ui
    restart: always
    networks:
      - back-net
    ports:
      - "8760:8080"
    depends_on:
      - skywalking-oap
    environment:
      collector.ribbon.listOfServers: skywalking-oap:12800
```
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
