### ISSUE TITLE
[Collector] The OperationName not display

### ISSUE THREAD

**Issue by alex8224** [apache/incubator-skywalking#642]
Please answer these questions before submitting your issue.

### What version of sky-walking are you using?
v3.2.5

### What version of your OS?
centos 6.5 64bit

### What version of your JRE?
java8

### Project Framework?
SpringBoots 1.4.1 + Mybatis + dubbo 

### Storage
ElasticSearch 5.5.1

### What did you do?
Click https://pan.baidu.com/s/1o87kbxC to show screenshot

###Collection applicaiton.yml

```yml
#cluster:                                                    
#  zookeeper:                                                
#    hostPort: localhost:2181                                
#    sessionTimeout: 100000                                  
naming:                                                      
  jetty:                                                     
    host: 10.0.98.22                                         
    port: 10800                                              
    context_path: /                                          
remote:                                                      
  gRPC:                                                      
    host: 10.0.98.22                                         
    port: 11800                                              
agent_gRPC:                                                  
  gRPC:                                                      
    host: 10.0.98.22                                         
    port: 11800                                              
agent_jetty:                                                 
  jetty:                                                     
    host: 10.0.98.22                                         
    port: 12800                                              
    context_path: /                                          
agent_stream:                                                
  default:                                                   
    buffer_file_path: ../buffer/                             
    buffer_offset_max_file_size: 10M                         
    buffer_segment_max_file_size: 500M                       
ui:                                                          
  jetty:                                                     
    host: 10.0.98.22                                         
    port: 12800                                              
    context_path: /                                          
storage:                                                     
  elasticsearch:                                             
    cluster_name: CollectorDBCluster                         
    cluster_transport_sniffer: true                          
    cluster_nodes: localhost:9300                            
    index_shards_number: 2                                   
    index_replicas_number: 0                                 
```
