### ISSUE TITLE
The path of Collector buffer dictionary is incorrect

### ISSUE THREAD

**Issue by ascrutae** [apache/incubator-skywalking#915]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

### Bug description
The path of Collector buffer directory is not under the `COLLECTOR_HOME` directory when the start script is not execute in bin directory

**Comment by peng-yongsheng** [comment]
Setting the path in application.yml
```
analysis_segment_parser:
  default:
    bufferFilePath: ../buffer/
    bufferOffsetMaxFileSize: 10M
    bufferSegmentMaxFileSize: 500M
```
